version: '3'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/webapp
    depends_on:
      - db
    environment:
      - BASEURL=test.kiichi7.com:5000
      - MONGO_INITDB_DATABSE=test
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABSE=test
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test